name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install react@^18.2.0 react-dom@^18.2.0 react-scripts@5.0.1 lucide-react@^0.263.1
        npm install -D tailwindcss@^3.3.0 autoprefixer@^10.4.14 postcss@^8.4.24

    - name: Build project
      run: npm run build

    - name: Check build artifacts
      run: |
        ls -la build/
        echo "Build completed successfully!"

  deploy-preview:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install and build
      run: |
        npm install react@^18.2.0 react-dom@^18.2.0 react-scripts@5.0.1 lucide-react@^0.263.1
        npm install -D tailwindcss@^3.3.0 autoprefixer@^10.4.14 postcss@^8.4.24
        npm run build

    - name: Deploy to Netlify (Preview)
      uses: nwtgck/actions-netlify@v1.2
      with:
        publish-dir: './build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}